### ISSUE TITLE
Providing a CLI to search for characters

### ISSUE THREAD

**Issue by Lucas-C** [eversport/node-unicodetable#10]
Hi.

I'm looking for a CLI tool that I could use to search for UTF8 characters given some keywords.

I thought maybe your tool could be extended to do so ?

If you agree on the idea, I can try to send a PR.

Regards

**Comment by tdanecker** [comment]
Hi Lucas!

I like the idea! But I would keep this package rather minimal as it is used as a dependency quite heavily (e.g. by the slug package which again is used quite a log).

How about a separate `unicode-cli` package that just depends on this one? I think this would be the best way to go about it!

**Comment by Lucas-C** [comment]
Good idea :)

**Comment by Lucas-C** [comment]
Created ! https://github.com/Lucas-C/unicode-search
