### ISSUE TITLE
Lite version

### ISSUE THREAD

**Issue by tech4him1** [eversport/node-unicodetable#11]
Would you consider making (or accepting a PR for) a "lite" version of the unicode table that will only have an array of the `symbol`s?

**Comment by tdanecker** [comment]
Hm, I'm not sure how that'd look like. But feel free to also just fork this project and publish a trimmed down version just for the symbols! I'd definitely encourage that!

**Comment by tech4him1** [comment]
Would you be open to a PR that would add support for this?

**Comment by tdanecker** [comment]
Can you describe in more detail what you mean? It might make more sense to publish it as a separate package if I understand your intentions correctly. Or do you mean the PR you opened?

**Comment by tech4him1** [comment]
@tdanecker Yes, it would be a separate package, but I'm wondering if it would be best to host both of them in the same repo. The other PR is not directly related, but I'll work on it first and then get back to this one.

**Comment by tech4him1** [comment]
@tdanecker I'll go ahead and close this for now and work on building it as a separate package. Thank you for your help!

**Comment by tech4him1** [comment]
@tdanecker Are you planning on merging #13 right away or waiting/testing it a little more? I'm just wondering because having it merged will make it much easier to build a "lite" version, but I can do it a different way if you don't really want to merge it.

**Comment by tech4him1** [comment]
https://www.npmjs.com/package/unicode-tables
