### ISSUE TITLE
Problems downloading UnicodeData.txt on windows

### ISSUE THREAD

**Issue by sdesalas** [eversport/node-unicodetable#6]
```
yarn install v0.21.3
[1/4] Resolving packages...
warning node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "snapsvg-cjs@0.0.4" has unmet peer dependency "eve@~0.4.2".
[4/4] Building fresh packages...
error C:\projects\LaserWeb4\node_modules\unicode: Command failed.
Exit code: 1
Command: C:\windows\system32\cmd.exe
Arguments: /d /s /c node install.js
Directory: C:\projects\LaserWeb4\node_modules\unicode
Output:
try to read file /usr/share/unicode/UnicodeData.txt …
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to read file UnicodeData.txt …
UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
Error while downloading UnicodeData.txt: Error: connect ETIMEDOUT 216.97.88.9:80
```

Note that this issue has also been noticed by other projects that use this library as a dependency, namely [docpad](https://github.com/docpad/docpad/issues/647#issuecomment-25925324), [keystone](https://github.com/keystonejs/keystone/issues/2400) and [dodo](https://github.com/dodo/node-unicodetable/issues/19), they are all trying to work out ways around the issue but would be great if it could be fixed here instead. Thanks!! 👍

**Comment by sdesalas** [comment]
Ah thats ok, closing. Didnt realise this was a fork, I'll post in main.

**Comment by tdanecker** [comment]
you're at the right place here ;) the original repo is stale for quite some time. have you tried the new version of the library (9.0.1)? it should be fixed with that version. we had the same problem and this was also the reason for this fork.

**Comment by sdesalas** [comment]
Thanks, I worked out there was an env variable `NODE_UNICODETABLE_UNICODEDATA_TXT ` that can be used to point to a local version of the file so figured how to work around it.

https://github.com/dodo/node-unicodetable/issues/16#issuecomment-294059837
